apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fluentd
spec:
  replicas: 3 # 3 Pods should exist at all times.
  selector:  # Pods label should be defined in ReplicaSet label selector
    matchLabels:
      app: logging-container
  template:
    metadata:
      name: logging-container-pod
      labels:
        app: logging-container # Atleast 1 Pod label should match with ReplicaSet Label Selector
    spec:
      containers:
      - name: logging-container
        image: fluentd:latest
        ports:
          - containerPort: 80